### PR TITLE
Ka/user menu

### PR DESCRIPTION
**Pull request by rayanb**

### CODE REVIEW

**Comment by kevalwell** [comment]
Did you fix the user menu in this?

**Comment by rayanb** [comment]
Yes

**Comment by kevalwell** [comment]
Ahh lol I did too.. But that's perfect thank you! You should come to nj for
dinner next Sunday with my family

**Comment by rayanb** [comment]
haha thank you so much for the invite ! It's far dude you guys should come
to new york !!

2015-02-28 19:39 GMT-05:00 Kevin Alwell notifications@github.com:

> Ahh lol I did too.. But that's perfect thank you! You should come to nj for
> dinner next Sunday with my family
>

**Comment by rayanb** [comment]
The branch works and I made the sessions finally work

2015-02-28 19:42 GMT-05:00 Boutaleb Rayan rayanbouts@gmail.com:

> haha thank you so much for the invite ! It's far dude you guys should come
> to new york !!
> 
> 2015-02-28 19:39 GMT-05:00 Kevin Alwell notifications@github.com:
> 
> Ahh lol I did too.. But that's perfect thank you! You should come to nj for
> 
> > dinner next Sunday with my family
> >

**Pull request merged**
