### PR TITLE
Css done for create Message && User Page

### PR DESCRIPTION
**Pull request by kevalwell**
@JeffT23 @rayanb Hey guys, I added user_page CSS, && message create CSS. Merge with master if you like

### CODE REVIEW

**Comment by rayanb** [comment]
Hey guys I'm trying to refactor/connect the dots, can you not push to
master from now on until I have finished please ?? Also, I'd like to give
you guys some best practice tips:
- you should add stylesheets in the layout file, it is not correct to add
  another html header in each file
- changing the logout/login in the layout is much better practice than
  doing it manually on each page because once you'll have a 100 pages
  website, it will be harder to manually paste login logout everywhere
- you don't need a logout.erb file so that the '/logout' link goes to the
  '/logout' route, you should render another file : in that case login.erb
  ...
  -Otherwise, super work guys I'm so proud of you haha !

2015-03-01 10:45 GMT-05:00 JeffT23 notifications@github.com:

**Comment by kevalwell** [comment]
Okay perfect thank you

**Comment by JeffT23** [comment]
Yup, I figured it wasn't best practice.  Thought we would add everything to layout once we had all the moving pieces. 

Let us know when you are done buddy, I won't push anything.  

Jeff

**Comment by rayanb** [comment]
I pushed to rb/final you guys accept my pull request

**Pull request merged**
